CREATE TABLE CLIENT (
    ID_CLIENT INT PRIMARY KEY AUTO_INCREMENT,
    client_name VARCHAR(100) NOT NULL,
    client_email VARCHAR(100) UNIQUE NOT NULL,
);

CREATE TABLE DESTINATION (
    ID_DESTINATION INT PRIMARY KEY AUTO_INCREMENT,
    destination_name VARCHAR(100) NOT NULL,
    destination_type ENUM('National', 'International') NOT NULL,
    destination_description TEXT,
    destination_base_price DECIMAL(10,2) NOT NULL
);

CREATE TABLE PACKAGE (
    ID_PACKAGE INT PRIMARY KEY AUTO_INCREMENT,
    package_name VARCHAR(100) NOT NULL,
    package_description TEXT,
    package_price DECIMAL(10,2) NOT NULL,
    package_type ENUM('Promotional', 'Customized') NOT NULL
);

CREATE TABLE RESERVATION (
    ID_RESERVATION INT PRIMARY KEY AUTO_INCREMENT,
    reservation_Date DATE NOT NULL,
    Total_Value DECIMAL(10,2) NOT NULL,
    ID_CLIENT INT NOT NULL,
    ID_PACKAGE INT NOT NULL,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    FOREIGN KEY (ID_PACKAGE) REFERENCES PACKAGE(ID_PACKAGE)
);

CREATE TABLE PACKAGE_DESTINATION (
    ID_PACKAGE INT,
    ID_DESTINATION INT,
    PRIMARY KEY (ID_PACKAGE, ID_DESTINATION),
    FOREIGN KEY (ID_PACKAGE) REFERENCES PACKAGE(ID_PACKAGE),
    FOREIGN KEY (ID_DESTINATION) REFERENCES DESTINATION(ID_DESTINATION)
);

CREATE INDEX idx_reservation_date ON RESERVATION(Reservation_Date);
